import type { Category } from './types'

export const categories: Category[] = [
  {
    id: '1',
    name: '餐饮美食',
    icon: '🍔',
    color: '#FF6B6B',
    children: [
      { id: '1-1', name: '早餐', icon: '🍳', color: '#FF8E8E' },
      { id: '1-2', name: '午餐', icon: '🍚', color: '#FF8E8E' },
      { id: '1-3', name: '晚餐', icon: '🍜', color: '#FF8E8E' },
      { id: '1-4', name: '零食饮料', icon: '🥤', color: '#FF8E8E' },
      { id: '1-5', name: '外卖', icon: '🛵', color: '#FF8E8E' },
      { id: '1-6', name: '餐厅', icon: '🍽️', color: '#FF8E8E' },
      { id: '1-7', name: '咖啡茶饮', icon: '☕', color: '#FF8E8E' },
      { id: '1-8', name: '水果零食', icon: '🍎', color: '#FF8E8E' },
    ],
  },
  {
    id: '2',
    name: '交通出行',
    icon: '🚗',
    color: '#4ECDC4',
    children: [
      { id: '2-1', name: '地铁公交', icon: '🚇', color: '#6DD5D8' },
      { id: '2-2', name: '打车', icon: '🚖', color: '#6DD5D8' },
      { id: '2-3', name: '自驾', icon: '🚙', color: '#6DD5D8' },
      { id: '2-4', name: '火车飞机', icon: '✈️', color: '#6DD5D8' },
      { id: '2-5', name: '自行车', icon: '🚲', color: '#6DD5D8' },
      { id: '2-6', name: '共享单车', icon: '🚴', color: '#6DD5D8' },
      { id: '2-7', name: '停车费', icon: '🅿️', color: '#6DD5D8' },
      { id: '2-8', name: '加油', icon: '⛽', color: '#6DD5D8' },
    ],
  },
  {
    id: '3',
    name: '购物消费',
    icon: '🛒',
    color: '#45B7D1',
    children: [
      { id: '3-1', name: '服装鞋帽', icon: '👕', color: '#5BC0DE' },
      { id: '3-2', name: '数码产品', icon: '📱', color: '#5BC0DE' },
      { id: '3-3', name: '家电家居', icon: '🏠', color: '#5BC0DE' },
      { id: '3-4', name: '美妆护肤', icon: '💄', color: '#5BC0DE' },
      { id: '3-5', name: '母婴用品', icon: '🍼', color: '#5BC0DE' },
      { id: '3-6', name: '日用百货', icon: '🧴', color: '#5BC0DE' },
      { id: '3-7', name: '书籍文具', icon: '📚', color: '#5BC0DE' },
    ],
  },
  {
    id: '4',
    name: '休闲娱乐',
    icon: '🎮',
    color: '#9B59B6',
    children: [
      { id: '4-1', name: '电影演出', icon: '🎬', color: '#BB8FCE' },
      { id: '4-2', name: '游戏娱乐', icon: '🎮', color: '#BB8FCE' },
      { id: '4-3', name: '健身运动', icon: '🏃', color: '#BB8FCE' },
      { id: '4-4', name: '旅游度假', icon: '✈️', color: '#BB8FCE' },
      { id: '4-5', name: '宠物', icon: '🐱', color: '#BB8FCE' },
      { id: '4-6', name: 'KTV', icon: '🎤', color: '#BB8FCE' },
      { id: '4-7', name: '按摩美容', icon: '💆', color: '#BB8FCE' },
    ],
  },
  {
    id: '5',
    name: '居住缴费',
    icon: '🏠',
    color: '#3498DB',
    children: [
      { id: '5-1', name: '房租水电', icon: '💡', color: '#5DADE2' },
      { id: '5-2', name: '物业费', icon: '📋', color: '#5DADE2' },
      { id: '5-3', name: '宽带费', icon: '📡', color: '#5DADE2' },
      { id: '5-4', name: '网费', icon: '🌐', color: '#5DADE2' },
      { id: '5-5', name: '燃气费', icon: '🔥', color: '#5DADE2' },
      { id: '5-6', name: '水费', icon: '💧', color: '#5DADE2' },
      { id: '5-7', name: '电费', icon: '⚡', color: '#5DADE2' },
      { id: '5-8', name: '维修费', icon: '🔧', color: '#5DADE2' },
    ],
  },
  {
    id: '6',
    name: '医疗健康',
    icon: '🏥',
    color: '#E74C3C',
    children: [
      { id: '6-1', name: '药店', icon: '💊', color: '#EC7063' },
      { id: '6-2', name: '医院', icon: '🏥', color: '#EC7063' },
      { id: '6-3', name: '保健品', icon: '🧪', color: '#EC7063' },
      { id: '6-4', name: '牙医', icon: '🦷', color: '#EC7063' },
      { id: '6-5', name: '眼镜', icon: '👓', color: '#EC7063' },
      { id: '6-6', name: '运动装备', icon: '🏃', color: '#EC7063' },
      { id: '6-7', name: '体检', icon: '💉', color: '#EC7063' },
    ],
  },
  {
    id: '7',
    name: '教育学习',
    icon: '📚',
    color: '#2ECC71',
    children: [
      { id: '7-1', name: '课培训', icon: '🎓', color: '#58D68D' },
      { id: '7-2', name: '书籍资料', icon: '📖', color: '#58D68D' },
      { id: '7-3', name: '在线课程', icon: '💻', color: '#58D68D' },
      { id: '7-4', name: '学习用品', icon: '✏️', color: '#58D68D' },
      { id: '7-5', name: '辅导费用', icon: '📝', color: '#58D68D' },
    ],
  },
  {
    id: '8',
    name: '人情往来',
    icon: '🎁',
    color: '#F39C12',
    children: [
      { id: '8-1', name: '礼金红包', icon: '红包', color: '#F5B041' },
      { id: '8-2', name: '聚会聚餐', icon: '🎉', color: '#F5B041' },
      { id: '8-3', name: '生日礼物', icon: '🎂', color: '#F5B041' },
      { id: '8-4', name: '节日红包', icon: '🧧', color: '#F5B041' },
    ],
  },
  {
    id: '9',
    name: '工作相关',
    icon: '💼',
    color: '#16A085',
    children: [
      { id: '9-1', name: '办公用品', icon: '📄', color: '#1ABC9C' },
      { id: '9-2', name: '通讯费', icon: '📱', color: '#1ABC9C' },
      { id: '9-3', name: '商务差旅', icon: '✈️', color: '#1ABC9C' },
      { id: '9-4', name: '培训费', icon: '📚', color: '#1ABC9C' },
      { id: '9-5', name: '面试交通', icon: '🚗', color: '#1ABC9C' },
    ],
  },
  {
    id: '10',
    name: '其他支出',
    icon: '💰',
    color: '#7F8C8D',
    children: [
      { id: '10-1', name: '其他支出', icon: '📝', color: '#95A5A6' },
      { id: '10-2', name: '现金消费', icon: '💵', color: '#95A5A6' },
    ],
  },
]
